;*******************************************************************
; FRED\FUNCTION.INC
;
; Author: Stefan Bormann (s.bormann@tu-bs.de)
;
; SEE COPYRGHT.TXT FOR COPYRIGHT INFO!!!
;
; History:  980815sb  Created for simple one bit function config
;
;
; This module manages the mapping button->function bits
;*******************************************************************


	cblock
		functionconfig : 1	; 0=F0/F1/F2 1=F0/F3/F4
	endc
	
	


